### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [crate/docker-crate#116]
Hi,

I am trying to build crate for ```ARM64v8``` architecture and I am getting below error:
```
/data # crate
[2018-07-13T09:02:39,750][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna1009797097459244164.tmp: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/jna-3506402/jna1009797097459244164.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_171]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_171]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_171]
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:140) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_171]
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.initializeNatives(BootstrapProxy.java:104) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:162) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:267) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.1.4.jar:3.0.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.1.4.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) [crate-app-3.0.3.jar:3.0.3]
[2018-07-13T09:02:39,765][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2018-07-13T09:02:39,765][WARN ][o.e.b.Natives            ] cannot install system call filter because JNA is not available
[2018-07-13T09:02:39,767][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2018-07-13T09:02:39,770][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2018-07-13T09:02:39,770][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2018-07-13T09:02:39,770][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_FSIZE because JNA is not available

```

Can you please have a look and let me know what is missing.
If this gets resolved then Crate can be extended for ```arm64v8``` as well

#83 : checked this too.

Regards,

**Comment by odidev** [comment]
Tried multiple OS distro for Crate on ```arm64v8```

```
Centos 7: Working fine
Ubuntu 16.04: Working fine
Alpine 3.7: JVM crash issue
```

It seems that there is some issue with Alpine support for arm64v8.

**Comment by odidev** [comment]
Raised PR #117, in case we all agree to use ```Ubuntu``` based approach.

The changes are propely verified on ```Arm64v8``` architecutre and ```Amd64``` architecture as well.

Please do let me know if something else is required to see ```arm64v8``` in Crate official Docker.

Regards,

**Comment by lag-linaro** [comment]
I have pushed your PR to my CodeFresh CI account.

You can pull and test it with:

`docker run -ti --rm laglinaro/dockercrate:odidev-arm64-new-base-ubuntu`

**Comment by lag-linaro** [comment]
@odidev out of interest, did you try Alpine 3.8?

**Comment by odidev** [comment]
Alpine3.8 - No, I didn't

Did it work for you on this Distro?

**Comment by lag-linaro** [comment]
I haven't tested it.  It might be worth a go, since moving Alpine 3.7 => Alpine 3.8 might be less painful.

Could you please have a go?

**Comment by odidev** [comment]
@lag-linaro
Bad luck.
Alpine 3.8 doesn't work. It results in same crash like it's predecessors.

I think best way is to use changes in the raised PR and move to new distro.

**Comment by lag-linaro** [comment]
Very well.  It was worth a try.

BTW, did you see that https://github.com/crate/docker-crate/pull/128 was just merged?

**Comment by lag-linaro** [comment]
CentOS doesn't support AArch64 either.

**Comment by odidev** [comment]
But CentOS 7 does support AARCH64.
I am already using CentOS7 over the AARCH64 system at my end.

**Comment by lag-linaro** [comment]
So Crate now works on AArch64.

Could we please indicate support (by adding an `Architecture:` tag) in the up-coming Pull Request to Docker's Official Images repo: https://github.com/docker-library/official-images/pull/5088?

**Comment by mfussenegger** [comment]
@lag-linaro can you verify that it still works on AArch64 after the latest changes? We'll then have a look at including the `Architecture` tag in the up-coming PR (for the upcoming `3.2`, we won't be making these changes for `3.1` releases)

**Comment by J0WI** [comment]
You could also add `arm32v6`, `i386`, `ppc64le` and `s390x`. You may want to use a `generate-stackbrew-library.sh` for it, like other images in the official library do.

**Comment by lag-linaro** [comment]
Appologies @mfussenegger I didn't realise you'd pinged me.

Look like the point is moot now though:

  https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/crate/

Awesome work, thank you.

This Issue can now be closed.
