### ISSUE TITLE
Runtime issues with CrateDB on Power platform

### ISSUE THREAD

**Issue by junawaneshivani** [crate/docker-crate#153]
I have build the Dockerfile_3.1.j for version 3.2.4 on POWER architecture after applying the required elasticsearch image patch. [Dockerfile.txt](https://github.com/crate/docker-crate/files/2977530/Dockerfile.txt)

However, I am facing runtime issues related to NullPointerException. Following log is observed after executing ```$docker run -it -p 4200:4200 -p 4300:4300 crate:3.2.4```

```
org.elasticsearch.bootstrap.StartupException: java.lang.NullPointerException
        at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:31) ~[crate-app-3.2.4.jar:?]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:159) ~[crate-app-3.2.4.jar:?]
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:?]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:?]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) ~[crate-app-3.2.4.jar:?]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) ~[crate-app-3.2.4.jar:?]
Caused by: java.lang.NullPointerException
        at org.elasticsearch.bootstrap.BootstrapChecks$AllPermissionCheck.isAllPermissionGranted(BootstrapChecks.java:707) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapChecks$AllPermissionCheck.check(BootstrapChecks.java:697) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapChecks.check(BootstrapChecks.java:137) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapChecks.check(BootstrapChecks.java:93) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapChecks.check(BootstrapChecks.java:75) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapProxy$1.validateNodeBeforeAcceptingRequests(BootstrapProxy.java:199) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.node.Node.start(Node.java:755) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:206) ~[crate-app-3.2.4.jar:?]
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:266) ~[crate-app-3.2.4.jar:?]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) ~[crate-app-3.2.4.jar:?]
```
Any suggestion would be helpful.

**Comment by seut** [comment]
CrateDB uses it's own fork of Elasticsearch, using vanilla Elasticsearch JAR's together with CrateDB won't work at all. Also CrateDB > 3.1 must use this https://github.com/crate/docker-crate/blob/master/Dockerfile.j2.

**Comment by junawaneshivani** [comment]
@ seut Thanks for your inputs :smile: I was able to build and validate crateDB on Power by building its fork of Elasticsearch and using jar created out of it.

**Comment by seut** [comment]
@junawaneshivani Great to hear, I'm closing this then.
