### ISSUE TITLE
custom configuration fails to start

### ISSUE THREAD

**Issue by srinijalagam** [crate/docker-crate#87]
I have used below docker run command 

docker run -e CRATE_JAVA_OPTS="-Xms1024m -Xmx1024m" -p 4200:4200 -p 4300:4300 -p 5432:5432  --env CRATE_HEAP_SIZE=2g crate crate -Cnetwork.host=_site_

it works fine.

I have tried overriding the crate.yml with license and Host Based Authentication Configuration 

 docker run **-v /crate/config/crate.yml:/crate/config/crate.yml** -e CRATE_JAVA_OPTS="-Xms1024m -Xmx1024m" -p 4200:4200 -p 4300:4300 -p 5432:5432  --env CRATE_HEAP_SIZE=2g crate crate -Cnetwork.host=_site_

i get below error any , suggestions or references are appreicated

I have attached crate.yml ( note removed license data )
[crate-yaml.zip](https://github.com/crate/docker-crate/files/1242954/crate-yaml.zip)

Exception in thread "main" ElasticsearchParseException[malformed, expected settings to start with 'object', instead was [VALUE_STRING]]
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:73)
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:52)
        at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:50)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1037)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1026)
        at org.elasticsearch.node.internal.CrateSettingsPreparer.prepareEnvironment(CrateSettingsPreparer.java:67)
        at org.elasticsearch.bootstrap.BootstrapProxy.initialEnvironment(BootstrapProxy.java:219)
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:259)
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:117)
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:108)

**Comment by srinijalagam** [comment]
I have merged docker container crate.yml content to my local

# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs
that resolved the above error
